[build]
  publish = "dist"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[build.processing]
  skip_processing = false

[build.processing.forms]
  enabled = true

[build.processing.files]
  enabled = true